name: Meals Crawl

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 25 * *'
  

name: Push to Pages Branch

on:
  push:
    branches:
      - main

jobs:
  push_to_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Python script
      run: python main.py

    - name: Commit and push to Pages branch
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout -b pages
        git add .
        git commit -m "Update from main branch"
        git push origin pages

