name: Meals Crawl

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 25 * *'
  

jobs:
  crawl_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create or Checkout Pages branch
      run: |
        git fetch origin

    - name: Execute Python script
      run: python main.py

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout -b pages  # Change this line to checkout the 'pages' branch
        git add API/meals/latest.json
        git commit -a -m "Add changes"
        git pull

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pages  # Change this line to push to the 'pages' branch

